apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-server
  labels:
    app: python-server
spec:
  ## Must match the label defined in service.yaml
  selector:
    matchLabels:
      app: python-server
  replicas: 2
  template:
    metadata:
      labels:
        app: python-server
    spec:
      ## Define the container image to be used
      containers:
        - name: python-server
          image: ericgpinto/simple-python-app:v4
          env:
            - name: NAME
              valueFrom:
                configMapKeyRef:
                  name: pythonserver-env
                  key: NAME
            - name: AGE
              valueFrom:
                configMapKeyRef:
                  name: pythonserver-env
                  key: AGE
